config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  namespace :admin do
    resources :sells
    resources :suppliers
    resources :campaigns
    resources :discounts
    resources :services
    resources :products
    resources :clients
  end
  # mount Fae below your admin namespec
  mount Fae::Engine => '/admin'

  mount Sidekiq::Web => '/sidekiq'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/campaign.rb
class Campaign < ApplicationRecord
  include Fae::BaseModelConcern

  validates :title, presence: true
  validates :body, presence: true
  has_many :campaign_clients
  has_many :clients, through: :campaign_clients

  after_save :schedule_emails

  def fae_display_field
    title
  end

  def schedule_emails
    Client.all.each do |client|
      CampaignClient.create(campaign: self, client: client)
      CampaignJob.perform_later client, self.title, self.body
    end
  end
end

app/models/campaign_client.rb
class CampaignClient < ApplicationRecord
  belongs_to :campaign
  belongs_to :client
end

app/models/client.rb
class Client < ApplicationRecord
  include Fae::BaseModelConcern

  has_many :campaign_clients
  has_many :campaigns, through: :campaign_clients, dependent: :destroy

  validates :phone, presence: true
  validates :email,
            uniqueness: true,
            presence: true,
            format: {
                with: Fae.validation_helpers.email_regex,
                message: 'You need use a valid and unique email'
            }

  def fae_display_field
    name
  end

end

app/models/concerns/fae/authorization_concern.rb
module Fae
  module AuthorizationConcern
    extend ActiveSupport::Concern
    module ClassMethods

      # Use the access_map to define any controllers that need any special authorization
      # Fae comes with three default roles:
      # - super admin: CRUD all objects, INCLUDING users and root settings
      # - admin: CRUD all objects, INCLUDING users and EXCLUDING root settings
      # - users: CRUD all objects, EXCLUDING users and root settings

      # each item should have a string key of the plural controller name and
      # an array of role names for the value
      # use "content_blocks/#{page_name}" for content blocks

      # example:
      # {
      #  'people' => ['super admin', 'admin'],
      #  'content_blocks/about_us' => ['super admin']
      # }
      def access_map
        {}
      end

    end
  end
end

app/models/concerns/fae/navigation_concern.rb
module Fae
  module NavigationConcern
    extend ActiveSupport::Concern

    # define the navigation structure in this file
    # example structure:
    #
    # def structure
    #   [
    #     item('Top Nav Item 1', subitems: [
    #       item('Top Nav Dropdown Item 1', class: 'custom-class', path: some_named_route_path),
    #       item('Top Nav Dropdown Item 2', subitems: [
    #         item('Side Nav Item 1', subitems: [
    #           item('Side Nav Nested Item', path: some_named_route_path)
    #         ]),
    #         item('Side Nav Item 1', path: some_named_route_path)
    #       ]),
    #     ]),
    #     item('Pages', subitems: [
    #       item('Home', path: fae.edit_content_block_path('home')),
    #       item('About Us', path: fae.edit_content_block_path('about_us'))
    #     ])
    #   ]
    # end

    def structure
      [
          item('Manage', subitems: [
              item('Clients', path: admin_clients_path),
              item('Discounts', path: admin_discounts_path),
              item('Suppliers', path: admin_suppliers_path),
              item('Services', path: admin_services_path),
              item('Products', path: admin_products_path),
              item('Sells', path: admin_sells_path),
          ]),
          item('Marketing', subitems: [
              item('Campaigns', path: admin_campaigns_path)
          ]),
          item('+ Sell', path: '/admin/sells/new')
      ]
    end
  end
end

app/models/discount.rb
class Discount < ApplicationRecord
  include Fae::BaseModelConcern

  validates :title, uniqueness: true, presence: true
  validates :value, uniqueness: true, presence: true

  def fae_display_field
    title
  end


end

app/models/product.rb
class Product < ApplicationRecord
  include Fae::BaseModelConcern

  validates :title, uniqueness: true, presence: true
  validates :price, presence: true

  def fae_display_field
    title
  end

  has_fae_image :hero_image


  belongs_to :supplier
end

app/models/sell.rb
class Sell < ApplicationRecord
  include Fae::BaseModelConcern
  enum status: {finalizada: 0, cancelada: 1}
  validates :client, presence: true

  belongs_to :discount
  belongs_to :client

  has_many :sell_products
  has_many :products, through: :sell_products, dependent: :destroy

  has_many :sell_services
  has_many :services, through: :sell_services, dependent: :destroy

  before_save :set_total

  def fae_display_field
    id
  end

  def self.for_fae_index
    order(:id)
  end

  private

  def set_total
    total = 0
    self.products.each {|p| total += p.price}
    self.services.each {|s| total += s.price}

    if self.discount.present?
      total = total - self.discount.value
    end

    total = (total >= 0) ? total : 0
    self.total = total
  end
end

app/models/sell_product.rb
class SellProduct < ApplicationRecord
  belongs_to :product
  belongs_to :sell
end

app/models/sell_service.rb
class SellService < ApplicationRecord
  belongs_to :service
  belongs_to :sell
end

app/models/service.rb
class Service < ApplicationRecord
  include Fae::BaseModelConcern

  validates :title, uniqueness: true, presence: true
  validates :price, presence: true

  def fae_display_field
    title
  end

  has_fae_image :hero_image


end

app/models/supplier.rb
class Supplier < ApplicationRecord
  include Fae::BaseModelConcern

  validates :name, uniqueness: true, presence: true
  validates :phone, presence: true
  validates :email,
            uniqueness: true,
            presence: true,
            format: {
                with: Fae.validation_helpers.email_regex,
                message: 'You need use a valid and unique email'
            }

  def fae_display_field
    name
  end


end

app/controllers/admin/campaigns_controller.rb
module Admin
  class CampaignsController < Fae::BaseController

  end
end

app/controllers/admin/clients_controller.rb
module Admin
  class ClientsController < Fae::BaseController

  end
end

app/controllers/admin/discounts_controller.rb
module Admin
  class DiscountsController < Fae::BaseController

  end
end

app/controllers/admin/products_controller.rb
module Admin
  class ProductsController < Fae::BaseController

    private

    def build_assets
      @item.build_hero_image if @item.hero_image.blank?
    end

  end
end

app/controllers/admin/sells_controller.rb
module Admin
  class SellsController < Fae::BaseController
  before_action :adjust_enum, only: [:create, :update]

  def adjust_enum
    params[:sell][:status] = params[:sell][:status].to_i
  end
  end
end

app/controllers/admin/services_controller.rb
module Admin
  class ServicesController < Fae::BaseController

    private

    def build_assets
      @item.build_hero_image if @item.hero_image.blank?
    end

  end
end

app/controllers/admin/suppliers_controller.rb
module Admin
  class SuppliersController < Fae::BaseController

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/campaigns/_form.html.slim
= simple_form_for(['admin', @item]) do |f|
  header.content-header.js-content-header
    == render 'fae/shared/form_header', header: @klass_name
  == render 'fae/shared/errors'

  main.content
    = fae_input f, :title
    = fae_input f, :body

app/views/admin/campaigns/edit.html.slim
== render 'form'

app/views/admin/campaigns/index.html.slim
== render 'fae/shared/index_header', title: @klass_humanized.pluralize.titleize

main.content
  table.js-sort-column
    thead
      tr
        th Title
        th.-action-wide Modified
        th.-action data-sorter="false"

    tbody
      - if @items.present?
        - @items.each do |item|
          tr id=fae_sort_id(item)
            td = item.title
            td = fae_date_format item.updated_at
            td = fae_delete_button item
      - else
        tr: td colspan="3" No items found

app/views/admin/campaigns/new.html.slim
== render 'form'

app/views/admin/clients/_form.html.slim
= simple_form_for(['admin', @item]) do |f|
  header.content-header.js-content-header
    == render 'fae/shared/form_header', header: @klass_name
  == render 'fae/shared/errors'

  main.content
    = fae_input f, :name
    = fae_input f, :email
    = fae_input f, :observations
    = fae_input f, :phone

app/views/admin/clients/edit.html.slim
== render 'form'

app/views/admin/clients/index.html.slim
== render 'fae/shared/index_header', title: @klass_humanized.pluralize.titleize, csv: true

main.content
  table.js-sort-column
    thead
      tr
        th Name
        th Email
        th.-action-wide Modified
        th.-action data-sorter="false"

    tbody
      - if @items.present?
        - @items.each do |item|
          tr id=fae_sort_id(item)
            td = link_to item.fae_display_field, edit_admin_client_path(item)
            td = item.email
            td = fae_date_format item.updated_at
            td = fae_delete_button item
      - else
        tr: td colspan="3" No items found

app/views/admin/clients/new.html.slim
== render 'form'

app/views/admin/discounts/_form.html.slim
= simple_form_for(['admin', @item]) do |f|
  header.content-header.js-content-header
    == render 'fae/shared/form_header', header: @klass_name
  == render 'fae/shared/errors'

  main.content
    = fae_input f, :title
    = fae_prefix f, :value, prefix: '$', placeholder: '50.00'

app/views/admin/discounts/edit.html.slim
== render 'form'

app/views/admin/discounts/index.html.slim
== render 'fae/shared/index_header', title: @klass_humanized.pluralize.titleize

main.content
  table.js-sort-column
    thead
      tr
        th Title
        th.-action-wide Modified
        th.-action data-sorter="false"

    tbody
      - if @items.present?
        - @items.each do |item|
          tr id=fae_sort_id(item)
            td = link_to item.fae_display_field, edit_admin_discount_path(item)
            td = fae_date_format item.updated_at
            td = fae_delete_button item
      - else
        tr: td colspan="3" No items found

app/views/admin/discounts/new.html.slim
== render 'form'

app/views/admin/products/_form.html.slim
= simple_form_for(['admin', @item]) do |f|
  header.content-header.js-content-header
    == render 'fae/shared/form_header', header: @klass_name
  == render 'fae/shared/errors'

  main.content
    = fae_input f, :title
    = fae_input f, :description
    = fae_prefix f, :price, prefix: '$', placeholder: '50.00'
    = fae_input f, :observations

    = fae_association f, :supplier

    = fae_image_form f, :hero_image

app/views/admin/products/edit.html.slim
== render 'form'

app/views/admin/products/index.html.slim
== render 'fae/shared/index_header', title: @klass_humanized.pluralize.titleize

main.content
  table.js-sort-column
    thead
      tr
        th Title
        th Price
        th Supplier
        th.-action-wide Modified
        th.-action data-sorter="false"

    tbody
      - if @items.present?
        - @items.each do |item|
          tr id=fae_sort_id(item)
            td = link_to item.fae_display_field, edit_admin_product_path(item)
            td = item.price
            td = (item.supplier)? item.supplier.name : ''
            td = fae_date_format item.updated_at
            td = fae_delete_button item
      - else
        tr: td colspan="3" No items found

app/views/admin/products/new.html.slim
== render 'form'

app/views/admin/sells/_form.html.slim
= simple_form_for(['admin', @item]) do |f|
  header.content-header.js-content-header
    == render 'fae/shared/form_header', header: @klass_name
  == render 'fae/shared/errors'

  main.content
    = fae_association f, :products
    = fae_association f, :services

    = fae_association f, :discount
    = fae_association f, :client
    = fae_datepicker f, :date

    = fae_input f, :observations
    = fae_pulldown f, :status, size: 'long', collection: Sell.statuses.to_a, selected: Sell.statuses[@item.status]

app/views/admin/sells/edit.html.slim
== render 'form'

app/views/admin/sells/index.html.slim
== render 'fae/shared/index_header', title: @klass_humanized.pluralize.titleize, csv: true

main.content
  table.js-sort-column
    thead
      tr
        th Id
        th Date
        th Client
        th Total
        th.-action-wide Modified
        th.-action data-sorter="false"

    tbody
      - if @items.present?
        - @items.each do |item|
          tr id=fae_sort_id(item)
            td = link_to item.fae_display_field, edit_admin_sell_path(item)
            td = item.date
            td = item.client.name
            td = item.total
            td = fae_date_format item.updated_at
            td = fae_delete_button item
      - else
        tr: td colspan="3" No items found

app/views/admin/sells/new.html.slim
== render 'form'

app/views/admin/services/_form.html.slim
= simple_form_for(['admin', @item]) do |f|
  header.content-header.js-content-header
    == render 'fae/shared/form_header', header: @klass_name
  == render 'fae/shared/errors'

  main.content
    = fae_input f, :title
    = fae_input f, :description
    = fae_prefix f, :price, prefix: '$', placeholder: '50.00'
    = fae_input f, :observations


    = fae_image_form f, :hero_image

app/views/admin/services/edit.html.slim
== render 'form'

app/views/admin/services/index.html.slim
== render 'fae/shared/index_header', title: @klass_humanized.pluralize.titleize

main.content
  table.js-sort-column
    thead
      tr
        th Title
        th Price
        th.-action-wide Modified
        th.-action data-sorter="false"

    tbody
      - if @items.present?
        - @items.each do |item|
          tr id=fae_sort_id(item)
            td = link_to item.fae_display_field, edit_admin_service_path(item)
            td = item.price
            td = fae_date_format item.updated_at
            td = fae_delete_button item
      - else
        tr: td colspan="3" No items found

app/views/admin/services/new.html.slim
== render 'form'

app/views/admin/suppliers/_form.html.slim
= simple_form_for(['admin', @item]) do |f|
  header.content-header.js-content-header
    == render 'fae/shared/form_header', header: @klass_name
  == render 'fae/shared/errors'

  main.content
    = fae_input f, :name
    = fae_input f, :observations
    = fae_input f, :email
    = fae_input f, :phone

app/views/admin/suppliers/edit.html.slim
== render 'form'

app/views/admin/suppliers/index.html.slim
== render 'fae/shared/index_header', title: @klass_humanized.pluralize.titleize

main.content
  table.js-sort-column
    thead
      tr
        th Name
        th.-action-wide Modified
        th.-action data-sorter="false"

    tbody
      - if @items.present?
        - @items.each do |item|
          tr id=fae_sort_id(item)
            td = link_to item.fae_display_field, edit_admin_supplier_path(item)
            td = fae_date_format item.updated_at
            td = fae_delete_button item
      - else
        tr: td colspan="3" No items found

app/views/admin/suppliers/new.html.slim
== render 'form'